<?php

/**
 * Implements hook_permission().
 */
function demo_permission() {
  return array(
    'administer demo module' =>  array(
      'title' => t('Administer demo module'),
      'description' => t('Perform administration tasks for my module.'),
    ),
  );
}


/**
 * Implements hook_node_view().
 */
function demo_node_view($node, $view_mode, $langcode) {

   $node->content['demo_field'] = array(
     '#type' => 'markup',
     '#markup' => '<p>'.t('this is only a demo').'</p>',
     '#weight' => 10,
     //'#theme' => 'mymodule_my_additional_field',
   );

   $node->content['demo_list'] = array(
     '#items' => array('green', 'blue', 'red', 'black'),
     '#weight' => 10,
     '#theme' => 'item_list',
   );

}
